# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'recordingmGwrQw.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(374, 325)
        self.pages = QStackedWidget(Dialog)
        self.pages.setObjectName(u"pages")
        self.pages.setGeometry(QRect(10, 0, 361, 281))
        self.pages.setMaximumSize(QSize(16777215, 400))
        self.editMouseMovement = QWidget()
        self.editMouseMovement.setObjectName(u"editMouseMovement")
        self.mouseMovementGB = QGroupBox(self.editMouseMovement)
        self.mouseMovementGB.setObjectName(u"mouseMovementGB")
        self.mouseMovementGB.setGeometry(QRect(0, 0, 361, 281))
        self.movementAbsolute = QCheckBox(self.mouseMovementGB)
        self.movementAbsolute.setObjectName(u"movementAbsolute")
        self.movementAbsolute.setGeometry(QRect(170, 20, 151, 17))
        self.movementAbsolute.setChecked(True)
        self.movementX = QSpinBox(self.mouseMovementGB)
        self.movementX.setObjectName(u"movementX")
        self.movementX.setGeometry(QRect(21, 80, 51, 22))
        self.movementX.setMinimum(-10000)
        self.movementX.setMaximum(10000)
        self.movementX.setSingleStep(10)
        self.movementX.setValue(0)
        self.movementY = QSpinBox(self.mouseMovementGB)
        self.movementY.setObjectName(u"movementY")
        self.movementY.setGeometry(QRect(81, 80, 51, 22))
        self.movementY.setMinimum(-10000)
        self.movementY.setMaximum(10000)
        self.movementY.setSingleStep(10)
        self.movementY.setValue(0)
        self.label_3 = QLabel(self.mouseMovementGB)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 60, 47, 13))
        self.label_4 = QLabel(self.mouseMovementGB)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(90, 60, 47, 13))
        self.movementDuration = QDoubleSpinBox(self.mouseMovementGB)
        self.movementDuration.setObjectName(u"movementDuration")
        self.movementDuration.setGeometry(QRect(170, 80, 62, 22))
        self.movementDuration.setMaximum(999.990000000000009)
        self.movementDuration.setSingleStep(0.250000000000000)
        self.movementDuration.setValue(0.250000000000000)
        self.label_5 = QLabel(self.mouseMovementGB)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(170, 50, 91, 16))
        self.pages.addWidget(self.editMouseMovement)
        self.editMouseButton = QWidget()
        self.editMouseButton.setObjectName(u"editMouseButton")
        self.mouseButtonGB = QGroupBox(self.editMouseButton)
        self.mouseButtonGB.setObjectName(u"mouseButtonGB")
        self.mouseButtonGB.setGeometry(QRect(0, 0, 361, 281))
        self.mouseButtonActionType = QGroupBox(self.mouseButtonGB)
        self.mouseButtonActionType.setObjectName(u"mouseButtonActionType")
        self.mouseButtonActionType.setGeometry(QRect(230, 50, 101, 119))
        self.verticalLayout_3 = QVBoxLayout(self.mouseButtonActionType)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.typeButtonClick = QRadioButton(self.mouseButtonActionType)
        self.typeButtonClick.setObjectName(u"typeButtonClick")

        self.verticalLayout_3.addWidget(self.typeButtonClick)

        self.typeButtonDoubleClick = QRadioButton(self.mouseButtonActionType)
        self.typeButtonDoubleClick.setObjectName(u"typeButtonDoubleClick")

        self.verticalLayout_3.addWidget(self.typeButtonDoubleClick)

        self.typeButtonHold = QRadioButton(self.mouseButtonActionType)
        self.typeButtonHold.setObjectName(u"typeButtonHold")

        self.verticalLayout_3.addWidget(self.typeButtonHold)

        self.typeButtonRelease = QRadioButton(self.mouseButtonActionType)
        self.typeButtonRelease.setObjectName(u"typeButtonRelease")

        self.verticalLayout_3.addWidget(self.typeButtonRelease)

        self.label_2 = QLabel(self.mouseButtonGB)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 80, 47, 13))
        self.mouseButtonSelection = QComboBox(self.mouseButtonGB)
        self.mouseButtonSelection.addItem("")
        self.mouseButtonSelection.addItem("")
        self.mouseButtonSelection.addItem("")
        self.mouseButtonSelection.setObjectName(u"mouseButtonSelection")
        self.mouseButtonSelection.setGeometry(QRect(20, 100, 91, 22))
        self.pages.addWidget(self.editMouseButton)
        self.editMouseWheel = QWidget()
        self.editMouseWheel.setObjectName(u"editMouseWheel")
        self.mouseWheelGB = QGroupBox(self.editMouseWheel)
        self.mouseWheelGB.setObjectName(u"mouseWheelGB")
        self.mouseWheelGB.setGeometry(QRect(0, 0, 361, 281))
        self.label_6 = QLabel(self.mouseWheelGB)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 110, 128, 13))
        self.mouseWheelDelta = QSpinBox(self.mouseWheelGB)
        self.mouseWheelDelta.setObjectName(u"mouseWheelDelta")
        self.mouseWheelDelta.setGeometry(QRect(50, 140, 42, 22))
        self.mouseWheelDelta.setMinimum(-100)
        self.mouseWheelDelta.setMaximum(100)
        self.pages.addWidget(self.editMouseWheel)
        self.editKeyboardButton = QWidget()
        self.editKeyboardButton.setObjectName(u"editKeyboardButton")
        self.keyboardButtonGB = QGroupBox(self.editKeyboardButton)
        self.keyboardButtonGB.setObjectName(u"keyboardButtonGB")
        self.keyboardButtonGB.setGeometry(QRect(0, 0, 361, 281))
        self.keyboardButtonActionType = QGroupBox(self.keyboardButtonGB)
        self.keyboardButtonActionType.setObjectName(u"keyboardButtonActionType")
        self.keyboardButtonActionType.setGeometry(QRect(210, 40, 136, 96))
        self.verticalLayout_4 = QVBoxLayout(self.keyboardButtonActionType)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.typeKeyClick = QRadioButton(self.keyboardButtonActionType)
        self.typeKeyClick.setObjectName(u"typeKeyClick")

        self.verticalLayout_4.addWidget(self.typeKeyClick)

        self.typeKeyHold = QRadioButton(self.keyboardButtonActionType)
        self.typeKeyHold.setObjectName(u"typeKeyHold")

        self.verticalLayout_4.addWidget(self.typeKeyHold)

        self.typeKeyRelease = QRadioButton(self.keyboardButtonActionType)
        self.typeKeyRelease.setObjectName(u"typeKeyRelease")

        self.verticalLayout_4.addWidget(self.typeKeyRelease)

        self.keyboardButtonSelection = QLineEdit(self.keyboardButtonGB)
        self.keyboardButtonSelection.setObjectName(u"keyboardButtonSelection")
        self.keyboardButtonSelection.setGeometry(QRect(30, 70, 113, 20))
        self.keyboardButtonSelection.setMaxLength(1)
        self.keyboardButtonSelection.setCursorPosition(0)
        self.label_9 = QLabel(self.keyboardButtonGB)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 50, 52, 13))
        self.pages.addWidget(self.editKeyboardButton)
        self.editKeyboardHotkey = QWidget()
        self.editKeyboardHotkey.setObjectName(u"editKeyboardHotkey")
        self.keyboardHotkeyGB = QGroupBox(self.editKeyboardHotkey)
        self.keyboardHotkeyGB.setObjectName(u"keyboardHotkeyGB")
        self.keyboardHotkeyGB.setGeometry(QRect(0, 0, 361, 281))
        self.keyboardHotkeySelection = QKeySequenceEdit(self.keyboardHotkeyGB)
        self.keyboardHotkeySelection.setObjectName(u"keyboardHotkeySelection")
        self.keyboardHotkeySelection.setGeometry(QRect(40, 80, 113, 20))
        self.label_16 = QLabel(self.keyboardHotkeyGB)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(40, 50, 134, 13))
        self.pages.addWidget(self.editKeyboardHotkey)
        self.editKeyboardWrite = QWidget()
        self.editKeyboardWrite.setObjectName(u"editKeyboardWrite")
        self.keyboardWriteGB = QGroupBox(self.editKeyboardWrite)
        self.keyboardWriteGB.setObjectName(u"keyboardWriteGB")
        self.keyboardWriteGB.setGeometry(QRect(0, 0, 361, 281))
        self.keyboardWriteTextfield = QTextEdit(self.keyboardWriteGB)
        self.keyboardWriteTextfield.setObjectName(u"keyboardWriteTextfield")
        self.keyboardWriteTextfield.setGeometry(QRect(10, 20, 341, 251))
        self.keyboardWriteTextfield.setAcceptRichText(False)
        self.pages.addWidget(self.editKeyboardWrite)
        self.editWaitMouse = QWidget()
        self.editWaitMouse.setObjectName(u"editWaitMouse")
        self.waitMouseGB = QGroupBox(self.editWaitMouse)
        self.waitMouseGB.setObjectName(u"waitMouseGB")
        self.waitMouseGB.setGeometry(QRect(0, 0, 361, 281))
        self.typeOfMouseAction = QComboBox(self.waitMouseGB)
        self.typeOfMouseAction.addItem("")
        self.typeOfMouseAction.addItem("")
        self.typeOfMouseAction.addItem("")
        self.typeOfMouseAction.setObjectName(u"typeOfMouseAction")
        self.typeOfMouseAction.setGeometry(QRect(70, 50, 197, 20))
        self.label_15 = QLabel(self.waitMouseGB)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(110, 30, 104, 13))
        self.typeOfMouseButton = QComboBox(self.waitMouseGB)
        self.typeOfMouseButton.addItem("")
        self.typeOfMouseButton.addItem("")
        self.typeOfMouseButton.addItem("")
        self.typeOfMouseButton.setObjectName(u"typeOfMouseButton")
        self.typeOfMouseButton.setGeometry(QRect(130, 110, 69, 22))
        self.label_17 = QLabel(self.waitMouseGB)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(90, 90, 161, 13))
        self.pages.addWidget(self.editWaitMouse)
        self.editWaitKeyboard = QWidget()
        self.editWaitKeyboard.setObjectName(u"editWaitKeyboard")
        self.waitKeyboardGB = QGroupBox(self.editWaitKeyboard)
        self.waitKeyboardGB.setObjectName(u"waitKeyboardGB")
        self.waitKeyboardGB.setGeometry(QRect(0, 0, 361, 281))
        self.waitKeyboardHotkey = QKeySequenceEdit(self.waitKeyboardGB)
        self.waitKeyboardHotkey.setObjectName(u"waitKeyboardHotkey")
        self.waitKeyboardHotkey.setGeometry(QRect(110, 80, 113, 20))
        self.label_19 = QLabel(self.waitKeyboardGB)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(50, 40, 245, 13))
        self.waitKeyboardSuppressor = QCheckBox(self.waitKeyboardGB)
        self.waitKeyboardSuppressor.setObjectName(u"waitKeyboardSuppressor")
        self.waitKeyboardSuppressor.setGeometry(QRect(60, 220, 229, 17))
        self.waitKeyboardSuppressor.setChecked(True)
        self.label_20 = QLabel(self.waitKeyboardGB)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(70, 240, 209, 13))
        self.pages.addWidget(self.editWaitKeyboard)
        self.editWaitNSeconds = QWidget()
        self.editWaitNSeconds.setObjectName(u"editWaitNSeconds")
        self.waitNSecondsGB = QGroupBox(self.editWaitNSeconds)
        self.waitNSecondsGB.setObjectName(u"waitNSecondsGB")
        self.waitNSecondsGB.setGeometry(QRect(0, 0, 361, 281))
        self.waitNSecondsTime = QDoubleSpinBox(self.waitNSecondsGB)
        self.waitNSecondsTime.setObjectName(u"waitNSecondsTime")
        self.waitNSecondsTime.setGeometry(QRect(91, 110, 131, 22))
        self.label_18 = QLabel(self.waitNSecondsGB)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(110, 90, 89, 13))
        self.pages.addWidget(self.editWaitNSeconds)
        self.editForLoop = QWidget()
        self.editForLoop.setObjectName(u"editForLoop")
        self.forLoopGB = QGroupBox(self.editForLoop)
        self.forLoopGB.setObjectName(u"forLoopGB")
        self.forLoopGB.setGeometry(QRect(0, 0, 361, 281))
        self.forLoopTimes = QSpinBox(self.forLoopGB)
        self.forLoopTimes.setObjectName(u"forLoopTimes")
        self.forLoopTimes.setGeometry(QRect(120, 200, 81, 22))
        self.forLoopTimes.setMinimum(1)
        self.forLoopTimes.setMaximum(9999999)
        self.label_7 = QLabel(self.forLoopGB)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(90, 180, 146, 13))
        self.pages.addWidget(self.editForLoop)
        self.editRecording = QWidget()
        self.editRecording.setObjectName(u"editRecording")
        self.RecordingGB = QGroupBox(self.editRecording)
        self.RecordingGB.setObjectName(u"RecordingGB")
        self.RecordingGB.setGeometry(QRect(0, 0, 231, 281))
        self.name = QLineEdit(self.RecordingGB)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(10, 40, 211, 20))
        self.label_8 = QLabel(self.RecordingGB)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 76, 13))
        self.start = QPushButton(self.RecordingGB)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(10, 250, 101, 23))
        self.preview = QPushButton(self.RecordingGB)
        self.preview.setObjectName(u"preview")
        self.preview.setGeometry(QRect(120, 250, 101, 23))
        self.cutSliderLeft = QSlider(self.RecordingGB)
        self.cutSliderLeft.setObjectName(u"cutSliderLeft")
        self.cutSliderLeft.setGeometry(QRect(10, 140, 101, 22))
        self.cutSliderLeft.setMinimum(0)
        self.cutSliderLeft.setMaximum(500)
        self.cutSliderLeft.setValue(0)
        self.cutSliderLeft.setOrientation(Qt.Horizontal)
        self.cutSliderRight = QSlider(self.RecordingGB)
        self.cutSliderRight.setObjectName(u"cutSliderRight")
        self.cutSliderRight.setGeometry(QRect(110, 140, 111, 22))
        self.cutSliderRight.setMinimum(0)
        self.cutSliderRight.setMaximum(500)
        self.cutSliderRight.setValue(0)
        self.cutSliderRight.setOrientation(Qt.Horizontal)
        self.cutSliderRight.setInvertedAppearance(True)
        self.label_10 = QLabel(self.RecordingGB)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(60, 120, 111, 16))
        self.timeBase = QLineEdit(self.RecordingGB)
        self.timeBase.setObjectName(u"timeBase")
        self.timeBase.setGeometry(QRect(10, 90, 113, 20))
        self.timeBase.setReadOnly(True)
        self.label_11 = QLabel(self.RecordingGB)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 70, 99, 13))
        self.timeFinal = QLineEdit(self.RecordingGB)
        self.timeFinal.setObjectName(u"timeFinal")
        self.timeFinal.setGeometry(QRect(50, 220, 131, 20))
        self.timeFinal.setReadOnly(True)
        self.label_12 = QLabel(self.RecordingGB)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(50, 200, 142, 13))
        self.cutTimeLeft = QDoubleSpinBox(self.RecordingGB)
        self.cutTimeLeft.setObjectName(u"cutTimeLeft")
        self.cutTimeLeft.setGeometry(QRect(10, 170, 62, 22))
        self.cutTimeLeft.setSingleStep(0.100000000000000)
        self.cutTimeRight = QDoubleSpinBox(self.RecordingGB)
        self.cutTimeRight.setObjectName(u"cutTimeRight")
        self.cutTimeRight.setGeometry(QRect(160, 170, 62, 22))
        self.cutTimeRight.setSingleStep(0.100000000000000)
        self.replaySpeed = QDoubleSpinBox(self.RecordingGB)
        self.replaySpeed.setObjectName(u"replaySpeed")
        self.replaySpeed.setGeometry(QRect(160, 90, 62, 22))
        self.replaySpeed.setMinimum(0.000000000000000)
        self.replaySpeed.setMaximum(10000.000000000000000)
        self.replaySpeed.setValue(1.000000000000000)
        self.label_14 = QLabel(self.RecordingGB)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(120, 70, 105, 13))
        self.whatToInclude = QGroupBox(self.editRecording)
        self.whatToInclude.setObjectName(u"whatToInclude")
        self.whatToInclude.setGeometry(QRect(240, 0, 121, 151))
        self.verticalLayout = QVBoxLayout(self.whatToInclude)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.includeClicks = QCheckBox(self.whatToInclude)
        self.includeClicks.setObjectName(u"includeClicks")
        self.includeClicks.setChecked(True)

        self.verticalLayout.addWidget(self.includeClicks)

        self.includeMoves = QCheckBox(self.whatToInclude)
        self.includeMoves.setObjectName(u"includeMoves")
        self.includeMoves.setChecked(True)

        self.verticalLayout.addWidget(self.includeMoves)

        self.includeWheel = QCheckBox(self.whatToInclude)
        self.includeWheel.setObjectName(u"includeWheel")
        self.includeWheel.setChecked(True)

        self.verticalLayout.addWidget(self.includeWheel)

        self.includeKeyboard = QCheckBox(self.whatToInclude)
        self.includeKeyboard.setObjectName(u"includeKeyboard")
        self.includeKeyboard.setChecked(True)

        self.verticalLayout.addWidget(self.includeKeyboard)

        self.hotkeys = QGroupBox(self.editRecording)
        self.hotkeys.setObjectName(u"hotkeys")
        self.hotkeys.setGeometry(QRect(240, 150, 121, 131))
        self.verticalLayout_2 = QVBoxLayout(self.hotkeys)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_13 = QLabel(self.hotkeys)
        self.label_13.setObjectName(u"label_13")

        self.verticalLayout_2.addWidget(self.label_13)

        self.recordingHotkey = QKeySequenceEdit(self.hotkeys)
        self.recordingHotkey.setObjectName(u"recordingHotkey")

        self.verticalLayout_2.addWidget(self.recordingHotkey)

        self.label = QLabel(self.hotkeys)
        self.label.setObjectName(u"label")

        self.verticalLayout_2.addWidget(self.label)

        self.previewHotkey = QKeySequenceEdit(self.hotkeys)
        self.previewHotkey.setObjectName(u"previewHotkey")

        self.verticalLayout_2.addWidget(self.previewHotkey)

        self.pages.addWidget(self.editRecording)
        self.universalButtonsGroup = QGroupBox(Dialog)
        self.universalButtonsGroup.setObjectName(u"universalButtonsGroup")
        self.universalButtonsGroup.setGeometry(QRect(10, 279, 361, 41))
        self.horizontalLayout = QHBoxLayout(self.universalButtonsGroup)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.save = QPushButton(self.universalButtonsGroup)
        self.save.setObjectName(u"save")

        self.horizontalLayout.addWidget(self.save)

        self.addToActions = QPushButton(self.universalButtonsGroup)
        self.addToActions.setObjectName(u"addToActions")

        self.horizontalLayout.addWidget(self.addToActions)

        self.cancel = QPushButton(self.universalButtonsGroup)
        self.cancel.setObjectName(u"cancel")

        self.horizontalLayout.addWidget(self.cancel)


        self.retranslateUi(Dialog)
        self.cancel.clicked.connect(Dialog.reject)

        self.pages.setCurrentIndex(10)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Edytor akcji", None))
        self.mouseMovementGB.setTitle(QCoreApplication.translate("Dialog", u"Opcje ruchu myszy", None))
        self.movementAbsolute.setText(QCoreApplication.translate("Dialog", u"Wsp\u00f3\u0142rz\u0119dne bezwzgl\u0119dne", None))
        self.movementX.setPrefix("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.movementDuration.setSuffix(QCoreApplication.translate("Dialog", u"s", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Czas trwania ruchu", None))
        self.mouseButtonGB.setTitle(QCoreApplication.translate("Dialog", u"Opcje naciskania przycisk\u00f3w myszy", None))
        self.mouseButtonActionType.setTitle(QCoreApplication.translate("Dialog", u"Typ czynno\u015bci", None))
        self.typeButtonClick.setText(QCoreApplication.translate("Dialog", u"Kliknij", None))
        self.typeButtonDoubleClick.setText(QCoreApplication.translate("Dialog", u"2x Kliknij", None))
        self.typeButtonHold.setText(QCoreApplication.translate("Dialog", u"Przytrzymaj", None))
        self.typeButtonRelease.setText(QCoreApplication.translate("Dialog", u"Pu\u015b\u0107", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Klawisz", None))
        self.mouseButtonSelection.setItemText(0, QCoreApplication.translate("Dialog", u"Lewy", None))
        self.mouseButtonSelection.setItemText(1, QCoreApplication.translate("Dialog", u"Prawy", None))
        self.mouseButtonSelection.setItemText(2, QCoreApplication.translate("Dialog", u"\u015arodkowy", None))

        self.mouseWheelGB.setTitle(QCoreApplication.translate("Dialog", u"Opcje ruchu k\u00f3\u0142ka myszy", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"O ile jednostek przesun\u0105\u0107?", None))
        self.keyboardButtonGB.setTitle(QCoreApplication.translate("Dialog", u"Opcje klikania w klawisz", None))
        self.keyboardButtonActionType.setTitle(QCoreApplication.translate("Dialog", u"Typ czynno\u015bci", None))
        self.typeKeyClick.setText(QCoreApplication.translate("Dialog", u"Kliknij klawisz", None))
        self.typeKeyHold.setText(QCoreApplication.translate("Dialog", u"Przytrzymaj klawisz", None))
        self.typeKeyRelease.setText(QCoreApplication.translate("Dialog", u"Pu\u015b\u0107 klawisz", None))
        self.keyboardButtonSelection.setInputMask("")
        self.keyboardButtonSelection.setText("")
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Co klikn\u0105\u0107?", None))
        self.keyboardHotkeyGB.setTitle(QCoreApplication.translate("Dialog", u"Skr\u00f3t klawiszowy", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Wprowad\u017a skr\u00f3t klawiszowy", None))
        self.keyboardWriteGB.setTitle(QCoreApplication.translate("Dialog", u"Wypisywanie tekstu z klawiatury", None))
        self.waitMouseGB.setTitle(QCoreApplication.translate("Dialog", u"Opcje czekania na akcj\u0119 myszy", None))
        self.typeOfMouseAction.setItemText(0, QCoreApplication.translate("Dialog", u"Wci\u015bni\u0119cie przycisku myszy", None))
        self.typeOfMouseAction.setItemText(1, QCoreApplication.translate("Dialog", u"Puszczenie przycisku myszy", None))
        self.typeOfMouseAction.setItemText(2, QCoreApplication.translate("Dialog", u"Podw\u00f3jne klikni\u0119cie przycisku myszy", None))

        self.label_15.setText(QCoreApplication.translate("Dialog", u"Na jak\u0105 akcj\u0119 czeka\u0107?", None))
        self.typeOfMouseButton.setItemText(0, QCoreApplication.translate("Dialog", u"Lewy", None))
        self.typeOfMouseButton.setItemText(1, QCoreApplication.translate("Dialog", u"Prawy", None))
        self.typeOfMouseButton.setItemText(2, QCoreApplication.translate("Dialog", u"\u015arodkowy", None))

        self.label_17.setText(QCoreApplication.translate("Dialog", u"Wybierz docelowy przycisk myszy", None))
        self.waitKeyboardGB.setTitle(QCoreApplication.translate("Dialog", u"Czekaj na akcj\u0119 klawiatury", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Wybierz na jak\u0105 akcj\u0119 klawiatury ma czeka\u0107 macro:", None))
        self.waitKeyboardSuppressor.setText(QCoreApplication.translate("Dialog", u"Czy wci\u015bni\u0119ty klawisz ma by\u0107 wyg\u0142uszony? ", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"(Inne aplikacje zarejesturj\u0105 jego wci\u015bni\u0119cia)", None))
        self.waitNSecondsGB.setTitle(QCoreApplication.translate("Dialog", u"Czekaj N sekund", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Ile sekund czeka\u0107?", None))
        self.forLoopGB.setTitle(QCoreApplication.translate("Dialog", u"Wykonaj N razy", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Ile razy ma si\u0119 wykona\u0107 p\u0119tla?", None))
        self.RecordingGB.setTitle(QCoreApplication.translate("Dialog", u"Kreator nagra\u0144 do u\u017cycia w makrach", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Nazwij nagranie", None))
        self.start.setText(QCoreApplication.translate("Dialog", u"Nagraj", None))
        self.preview.setText(QCoreApplication.translate("Dialog", u"Odtw\u00f3rz", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Przycinanie nagrania", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"D\u0142ugo\u015b\u0107 nagrania (s)", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Finalna d\u0142ugo\u015b\u0107 nagrania (s)", None))
        self.cutTimeLeft.setSuffix(QCoreApplication.translate("Dialog", u"s", None))
        self.cutTimeRight.setSuffix(QCoreApplication.translate("Dialog", u"s", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Pr\u0119dko\u015b\u0107 odtwarzania", None))
        self.whatToInclude.setTitle(QCoreApplication.translate("Dialog", u"Co odtwarza\u0107", None))
        self.includeClicks.setText(QCoreApplication.translate("Dialog", u"Klikni\u0119cia", None))
        self.includeMoves.setText(QCoreApplication.translate("Dialog", u"Ruch myszy", None))
        self.includeWheel.setText(QCoreApplication.translate("Dialog", u"Ruch scrolla", None))
        self.includeKeyboard.setText(QCoreApplication.translate("Dialog", u"Klawisze", None))
        self.hotkeys.setTitle(QCoreApplication.translate("Dialog", u"Skr\u00f3ty klawiszowe", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Skr\u00f3t do nagrywania", None))
        self.recordingHotkey.setKeySequence(QCoreApplication.translate("Dialog", u"Ctrl+R", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Skr\u00f3t do podgl\u0105du", None))
        self.previewHotkey.setKeySequence(QCoreApplication.translate("Dialog", u"Ctrl+P", None))
        self.universalButtonsGroup.setTitle("")
        self.save.setText(QCoreApplication.translate("Dialog", u"Zapisz", None))
#if QT_CONFIG(tooltip)
        self.addToActions.setToolTip(QCoreApplication.translate("Dialog", u"Dotyczy jedynie nagra\u0144", None))
#endif // QT_CONFIG(tooltip)
        self.addToActions.setText(QCoreApplication.translate("Dialog", u"Dodaj do czynno\u015bci", None))
        self.cancel.setText(QCoreApplication.translate("Dialog", u"Anuluj", None))
    # retranslateUi

