# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'recordingiYRwGu.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(382, 329)
        self.stackedWidget = QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 361, 311))
        self.recording = QWidget()
        self.recording.setObjectName(u"recording")
        self.Group = QGroupBox(self.recording)
        self.Group.setObjectName(u"Group")
        self.Group.setGeometry(QRect(0, 0, 231, 311))
        self.name = QLineEdit(self.Group)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(10, 40, 211, 20))
        self.label_8 = QLabel(self.Group)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 76, 13))
        self.addToActions = QPushButton(self.Group)
        self.addToActions.setObjectName(u"addToActions")
        self.addToActions.setGeometry(QRect(10, 280, 100, 23))
        self.start = QPushButton(self.Group)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(10, 250, 101, 23))
        self.preview = QPushButton(self.Group)
        self.preview.setObjectName(u"preview")
        self.preview.setGeometry(QRect(120, 250, 101, 23))
        self.cutSliderLeft = QSlider(self.Group)
        self.cutSliderLeft.setObjectName(u"cutSliderLeft")
        self.cutSliderLeft.setGeometry(QRect(10, 140, 101, 22))
        self.cutSliderLeft.setMinimum(0)
        self.cutSliderLeft.setMaximum(500)
        self.cutSliderLeft.setValue(0)
        self.cutSliderLeft.setOrientation(Qt.Horizontal)
        self.cutSliderRight = QSlider(self.Group)
        self.cutSliderRight.setObjectName(u"cutSliderRight")
        self.cutSliderRight.setGeometry(QRect(110, 140, 111, 22))
        self.cutSliderRight.setMinimum(0)
        self.cutSliderRight.setMaximum(500)
        self.cutSliderRight.setValue(0)
        self.cutSliderRight.setOrientation(Qt.Horizontal)
        self.cutSliderRight.setInvertedAppearance(True)
        self.label_10 = QLabel(self.Group)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(60, 120, 111, 16))
        self.timeBase = QLineEdit(self.Group)
        self.timeBase.setObjectName(u"timeBase")
        self.timeBase.setGeometry(QRect(10, 90, 113, 20))
        self.timeBase.setReadOnly(True)
        self.label_11 = QLabel(self.Group)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 70, 99, 13))
        self.timeFinal = QLineEdit(self.Group)
        self.timeFinal.setObjectName(u"timeFinal")
        self.timeFinal.setGeometry(QRect(50, 220, 131, 20))
        self.timeFinal.setReadOnly(True)
        self.label_12 = QLabel(self.Group)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(50, 200, 142, 13))
        self.cutTimeLeft = QDoubleSpinBox(self.Group)
        self.cutTimeLeft.setObjectName(u"cutTimeLeft")
        self.cutTimeLeft.setGeometry(QRect(10, 170, 62, 22))
        self.cutTimeLeft.setSingleStep(0.100000000000000)
        self.cutTimeRight = QDoubleSpinBox(self.Group)
        self.cutTimeRight.setObjectName(u"cutTimeRight")
        self.cutTimeRight.setGeometry(QRect(160, 170, 62, 22))
        self.cutTimeRight.setSingleStep(0.100000000000000)
        self.replaySpeed = QDoubleSpinBox(self.Group)
        self.replaySpeed.setObjectName(u"replaySpeed")
        self.replaySpeed.setGeometry(QRect(160, 90, 62, 22))
        self.replaySpeed.setMinimum(0.000000000000000)
        self.replaySpeed.setMaximum(10000.000000000000000)
        self.replaySpeed.setValue(1.000000000000000)
        self.label_14 = QLabel(self.Group)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(120, 70, 105, 13))
        self.cancel = QPushButton(self.Group)
        self.cancel.setObjectName(u"cancel")
        self.cancel.setGeometry(QRect(120, 280, 101, 23))
        self.whatToInclude = QGroupBox(self.recording)
        self.whatToInclude.setObjectName(u"whatToInclude")
        self.whatToInclude.setGeometry(QRect(240, 0, 121, 151))
        self.verticalLayout = QVBoxLayout(self.whatToInclude)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.includeClicks = QCheckBox(self.whatToInclude)
        self.includeClicks.setObjectName(u"includeClicks")
        self.includeClicks.setChecked(True)

        self.verticalLayout.addWidget(self.includeClicks)

        self.includeMoves = QCheckBox(self.whatToInclude)
        self.includeMoves.setObjectName(u"includeMoves")
        self.includeMoves.setChecked(True)

        self.verticalLayout.addWidget(self.includeMoves)

        self.includeWheel = QCheckBox(self.whatToInclude)
        self.includeWheel.setObjectName(u"includeWheel")
        self.includeWheel.setChecked(True)

        self.verticalLayout.addWidget(self.includeWheel)

        self.includeKeyboard = QCheckBox(self.whatToInclude)
        self.includeKeyboard.setObjectName(u"includeKeyboard")
        self.includeKeyboard.setChecked(True)

        self.verticalLayout.addWidget(self.includeKeyboard)

        self.hotkeys = QGroupBox(self.recording)
        self.hotkeys.setObjectName(u"hotkeys")
        self.hotkeys.setGeometry(QRect(240, 150, 121, 161))
        self.verticalLayout_2 = QVBoxLayout(self.hotkeys)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_13 = QLabel(self.hotkeys)
        self.label_13.setObjectName(u"label_13")

        self.verticalLayout_2.addWidget(self.label_13)

        self.recordingHotkey = QKeySequenceEdit(self.hotkeys)
        self.recordingHotkey.setObjectName(u"recordingHotkey")

        self.verticalLayout_2.addWidget(self.recordingHotkey)

        self.label = QLabel(self.hotkeys)
        self.label.setObjectName(u"label")

        self.verticalLayout_2.addWidget(self.label)

        self.previewHotkey = QKeySequenceEdit(self.hotkeys)
        self.previewHotkey.setObjectName(u"previewHotkey")

        self.verticalLayout_2.addWidget(self.previewHotkey)

        self.stackedWidget.addWidget(self.recording)
        self.mouseMovement = QWidget()
        self.mouseMovement.setObjectName(u"mouseMovement")
        self.groupBox = QGroupBox(self.mouseMovement)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 361, 311))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(170, 20, 151, 17))
        self.checkBox.setChecked(True)
        self.spinBox = QSpinBox(self.groupBox)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(21, 80, 51, 22))
        self.spinBox.setMinimum(-10000)
        self.spinBox.setMaximum(10000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setValue(0)
        self.spinBox_2 = QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(81, 80, 51, 22))
        self.spinBox_2.setMinimum(-10000)
        self.spinBox_2.setMaximum(10000)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setValue(0)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 60, 47, 13))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(90, 60, 47, 13))
        self.doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(170, 80, 62, 22))
        self.doubleSpinBox.setMaximum(999.990000000000009)
        self.doubleSpinBox.setSingleStep(0.250000000000000)
        self.doubleSpinBox.setValue(0.250000000000000)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(170, 50, 91, 16))
        self.stackedWidget.addWidget(self.mouseMovement)

        self.retranslateUi(Dialog)
        self.cancel.clicked.connect(Dialog.reject)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.Group.setTitle(QCoreApplication.translate("Dialog", u"Kreator nagra\u0144 do u\u017cycia w makrach", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Nazwij nagranie", None))
        self.addToActions.setText(QCoreApplication.translate("Dialog", u"Dodaj do czynno\u015bci", None))
        self.start.setText(QCoreApplication.translate("Dialog", u"Nagraj", None))
        self.preview.setText(QCoreApplication.translate("Dialog", u"Odtw\u00f3rz", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Przycinanie nagrania", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"D\u0142ugo\u015b\u0107 nagrania (s)", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Finalna d\u0142ugo\u015b\u0107 nagrania (s)", None))
        self.cutTimeLeft.setSuffix(QCoreApplication.translate("Dialog", u"s", None))
        self.cutTimeRight.setSuffix(QCoreApplication.translate("Dialog", u"s", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Pr\u0119dko\u015b\u0107 odtwarzania", None))
        self.cancel.setText(QCoreApplication.translate("Dialog", u"Anuluj", None))
        self.whatToInclude.setTitle(QCoreApplication.translate("Dialog", u"Co odtwarza\u0107", None))
        self.includeClicks.setText(QCoreApplication.translate("Dialog", u"Klikni\u0119cia", None))
        self.includeMoves.setText(QCoreApplication.translate("Dialog", u"Ruch myszy", None))
        self.includeWheel.setText(QCoreApplication.translate("Dialog", u"Ruch scrolla", None))
        self.includeKeyboard.setText(QCoreApplication.translate("Dialog", u"Klawisze", None))
        self.hotkeys.setTitle(QCoreApplication.translate("Dialog", u"Skr\u00f3ty klawiszowe", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Skr\u00f3t do nagrywania", None))
        self.recordingHotkey.setKeySequence(QCoreApplication.translate("Dialog", u"Ctrl+R", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Skr\u00f3t do podgl\u0105du", None))
        self.previewHotkey.setKeySequence(QCoreApplication.translate("Dialog", u"Ctrl+P", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Opcje ruchu myszy", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"Wsp\u00f3\u0142rz\u0119dne bezwzgl\u0119dne", None))
        self.spinBox.setPrefix("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.doubleSpinBox.setSuffix(QCoreApplication.translate("Dialog", u"s", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Czas trwania ruchu", None))
    # retranslateUi

