# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUIAYTrPk.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(792, 568)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(792, 568))
        MainWindow.setMaximumSize(QSize(792, 568))
        icon = QIcon()
        icon.addFile(u"ARZicon.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(50, 50))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.tabs = QTabWidget(self.centralwidget)
        self.tabs.setObjectName(u"tabs")
        self.tabs.setGeometry(QRect(10, 0, 781, 561))
        self.tabs.setFocusPolicy(Qt.ClickFocus)
        self.tabs.setIconSize(QSize(16, 16))
        self.macroTab = QWidget()
        self.macroTab.setObjectName(u"macroTab")
        self.macroDelete = QPushButton(self.macroTab)
        self.macroDelete.setObjectName(u"macroDelete")
        self.macroDelete.setGeometry(QRect(690, 500, 75, 23))
        self.macroEdit = QPushButton(self.macroTab)
        self.macroEdit.setObjectName(u"macroEdit")
        self.macroEdit.setGeometry(QRect(10, 500, 91, 23))
        self.macroNew = QPushButton(self.macroTab)
        self.macroNew.setObjectName(u"macroNew")
        self.macroNew.setGeometry(QRect(120, 500, 97, 23))
        self.macroTreeView = QTreeView(self.macroTab)
        self.macroTreeView.setObjectName(u"macroTreeView")
        self.macroTreeView.setGeometry(QRect(10, 20, 751, 471))
        self.tabs.addTab(self.macroTab, "")
        self.creatorTab = QWidget()
        self.creatorTab.setObjectName(u"creatorTab")
        self.creatorEditorGroup = QGroupBox(self.creatorTab)
        self.creatorEditorGroup.setObjectName(u"creatorEditorGroup")
        self.creatorEditorGroup.setGeometry(QRect(10, 10, 761, 521))
        self.creatorEditorDeleteFromMacro = QPushButton(self.creatorEditorGroup)
        self.creatorEditorDeleteFromMacro.setObjectName(u"creatorEditorDeleteFromMacro")
        self.creatorEditorDeleteFromMacro.setGeometry(QRect(130, 480, 101, 23))
        self.creatorEditorActions = QTreeWidget(self.creatorEditorGroup)
        __qtreewidgetitem = QTreeWidgetItem(self.creatorEditorActions)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        __qtreewidgetitem1 = QTreeWidgetItem(self.creatorEditorActions)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        __qtreewidgetitem2 = QTreeWidgetItem(self.creatorEditorActions)
        QTreeWidgetItem(__qtreewidgetitem2)
        QTreeWidgetItem(__qtreewidgetitem2)
        QTreeWidgetItem(__qtreewidgetitem2)
        QTreeWidgetItem(__qtreewidgetitem2)
        QTreeWidgetItem(self.creatorEditorActions)
        self.creatorEditorActions.setObjectName(u"creatorEditorActions")
        self.creatorEditorActions.setGeometry(QRect(20, 30, 211, 411))
        self.creatorEditorActions.setFrameShadow(QFrame.Sunken)
        self.creatorEditorActions.setAlternatingRowColors(True)
        self.creatorEditorAddToMacro = QPushButton(self.creatorEditorGroup)
        self.creatorEditorAddToMacro.setObjectName(u"creatorEditorAddToMacro")
        self.creatorEditorAddToMacro.setGeometry(QRect(130, 450, 101, 23))
        self.creatorEditorMoveUp = QPushButton(self.creatorEditorGroup)
        self.creatorEditorMoveUp.setObjectName(u"creatorEditorMoveUp")
        self.creatorEditorMoveUp.setGeometry(QRect(270, 450, 75, 23))
        self.creatorEditorMoveDown = QPushButton(self.creatorEditorGroup)
        self.creatorEditorMoveDown.setObjectName(u"creatorEditorMoveDown")
        self.creatorEditorMoveDown.setGeometry(QRect(270, 480, 75, 23))
        self.creatorEditorSave = QPushButton(self.creatorEditorGroup)
        self.creatorEditorSave.setObjectName(u"creatorEditorSave")
        self.creatorEditorSave.setGeometry(QRect(440, 480, 101, 23))
        self.creatorEditorName = QLineEdit(self.creatorEditorGroup)
        self.creatorEditorName.setObjectName(u"creatorEditorName")
        self.creatorEditorName.setGeometry(QRect(440, 450, 301, 20))
        self.label_9 = QLabel(self.creatorEditorGroup)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(360, 450, 71, 20))
        self.creatorEditorClear = QPushButton(self.creatorEditorGroup)
        self.creatorEditorClear.setObjectName(u"creatorEditorClear")
        self.creatorEditorClear.setGeometry(QRect(640, 480, 101, 23))
        self.creatorEditorDeleteFromActions = QPushButton(self.creatorEditorGroup)
        self.creatorEditorDeleteFromActions.setObjectName(u"creatorEditorDeleteFromActions")
        self.creatorEditorDeleteFromActions.setGeometry(QRect(20, 480, 103, 23))
        self.creatorEditorNewRecording = QPushButton(self.creatorEditorGroup)
        self.creatorEditorNewRecording.setObjectName(u"creatorEditorNewRecording")
        self.creatorEditorNewRecording.setGeometry(QRect(20, 450, 101, 23))
        self.label_8 = QLabel(self.creatorEditorGroup)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(270, 10, 152, 13))
        self.creatorEditorTreeView = QTreeView(self.creatorEditorGroup)
        self.creatorEditorTreeView.setObjectName(u"creatorEditorTreeView")
        self.creatorEditorTreeView.setGeometry(QRect(270, 30, 471, 411))
        self.creatorEditorTreeView.setAlternatingRowColors(True)
        self.creatorEditorTreeView.setTextElideMode(Qt.ElideMiddle)
        self.creatorEditorTreeView.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.creatorEditorTreeView.setWordWrap(True)
        self.creatorEditorTreeView.header().setDefaultSectionSize(200)
        self.previewButton = QPushButton(self.creatorEditorGroup)
        self.previewButton.setObjectName(u"previewButton")
        self.previewButton.setGeometry(QRect(550, 480, 75, 23))
        self.tabs.addTab(self.creatorTab, "")
        self.autoclickerTab = QWidget()
        self.autoclickerTab.setObjectName(u"autoclickerTab")
        self.AC_Mouse = QGroupBox(self.autoclickerTab)
        self.AC_Mouse.setObjectName(u"AC_Mouse")
        self.AC_Mouse.setGeometry(QRect(10, 10, 371, 521))
        self.AC_Time = QGroupBox(self.AC_Mouse)
        self.AC_Time.setObjectName(u"AC_Time")
        self.AC_Time.setGeometry(QRect(10, 20, 351, 181))
        self.AC_Hours = QSpinBox(self.AC_Time)
        self.AC_Hours.setObjectName(u"AC_Hours")
        self.AC_Hours.setGeometry(QRect(20, 90, 51, 22))
        self.AC_Hours.setMaximum(999)
        self.AC_Minutes = QSpinBox(self.AC_Time)
        self.AC_Minutes.setObjectName(u"AC_Minutes")
        self.AC_Minutes.setGeometry(QRect(110, 90, 51, 22))
        self.AC_Minutes.setMaximum(999)
        self.AC_Seconds = QSpinBox(self.AC_Time)
        self.AC_Seconds.setObjectName(u"AC_Seconds")
        self.AC_Seconds.setGeometry(QRect(190, 90, 51, 22))
        self.AC_Seconds.setMaximum(999)
        self.AC_Miliseconds = QSpinBox(self.AC_Time)
        self.AC_Miliseconds.setObjectName(u"AC_Miliseconds")
        self.AC_Miliseconds.setGeometry(QRect(280, 90, 51, 22))
        self.AC_Miliseconds.setMinimum(1)
        self.AC_Miliseconds.setMaximum(999)
        self.AC_Miliseconds.setValue(100)
        self.label = QLabel(self.AC_Time)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(270, 70, 71, 20))
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.AC_Time)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 70, 51, 20))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.AC_Time)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 70, 51, 20))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.AC_Time)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 70, 51, 20))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.AC_ClickHowManyTimesGroup = QGroupBox(self.AC_Mouse)
        self.AC_ClickHowManyTimesGroup.setObjectName(u"AC_ClickHowManyTimesGroup")
        self.AC_ClickHowManyTimesGroup.setGeometry(QRect(190, 210, 171, 271))
        self.AC_ClickNTimes = QRadioButton(self.AC_ClickHowManyTimesGroup)
        self.AC_ClickNTimes.setObjectName(u"AC_ClickNTimes")
        self.AC_ClickNTimes.setGeometry(QRect(10, 100, 47, 21))
        self.AC_ClickNTimesN = QSpinBox(self.AC_ClickHowManyTimesGroup)
        self.AC_ClickNTimesN.setObjectName(u"AC_ClickNTimesN")
        self.AC_ClickNTimesN.setGeometry(QRect(60, 100, 61, 22))
        self.AC_ClickNTimesN.setMinimum(1)
        self.AC_ClickNTimesN.setMaximum(9999999)
        self.AC_ClickNTimesN.setValue(1)
        self.label_7 = QLabel(self.AC_ClickHowManyTimesGroup)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 100, 21, 21))
        self.AC_ClickUntilStopped = QRadioButton(self.AC_ClickHowManyTimesGroup)
        self.AC_ClickUntilStopped.setObjectName(u"AC_ClickUntilStopped")
        self.AC_ClickUntilStopped.setGeometry(QRect(10, 130, 123, 17))
        self.AC_ClickUntilStopped.setChecked(True)
        self.groupBox = QGroupBox(self.AC_Mouse)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 210, 161, 271))
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")

        self.verticalLayout.addWidget(self.label_6)

        self.AC_WhichButton = QComboBox(self.groupBox)
        self.AC_WhichButton.addItem("")
        self.AC_WhichButton.addItem("")
        self.AC_WhichButton.addItem("")
        self.AC_WhichButton.setObjectName(u"AC_WhichButton")

        self.verticalLayout.addWidget(self.AC_WhichButton)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_3)

        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")

        self.verticalLayout.addWidget(self.label_5)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_2)

        self.AC_Stop = QPushButton(self.AC_Mouse)
        self.AC_Stop.setObjectName(u"AC_Stop")
        self.AC_Stop.setGeometry(QRect(190, 490, 171, 23))
        self.AC_Start = QPushButton(self.AC_Mouse)
        self.AC_Start.setObjectName(u"AC_Start")
        self.AC_Start.setGeometry(QRect(10, 490, 161, 23))
        self.AC_Keyboard = QGroupBox(self.autoclickerTab)
        self.AC_Keyboard.setObjectName(u"AC_Keyboard")
        self.AC_Keyboard.setGeometry(QRect(400, 10, 371, 521))
        self.AC_KeyboardTime = QGroupBox(self.AC_Keyboard)
        self.AC_KeyboardTime.setObjectName(u"AC_KeyboardTime")
        self.AC_KeyboardTime.setGeometry(QRect(10, 20, 351, 181))
        self.AC_KeyboardHours = QSpinBox(self.AC_KeyboardTime)
        self.AC_KeyboardHours.setObjectName(u"AC_KeyboardHours")
        self.AC_KeyboardHours.setGeometry(QRect(20, 90, 51, 22))
        self.AC_KeyboardHours.setMaximum(999)
        self.AC_KeyboardMinutes = QSpinBox(self.AC_KeyboardTime)
        self.AC_KeyboardMinutes.setObjectName(u"AC_KeyboardMinutes")
        self.AC_KeyboardMinutes.setGeometry(QRect(110, 90, 51, 22))
        self.AC_KeyboardMinutes.setMaximum(999)
        self.AC_KeyboardSeconds = QSpinBox(self.AC_KeyboardTime)
        self.AC_KeyboardSeconds.setObjectName(u"AC_KeyboardSeconds")
        self.AC_KeyboardSeconds.setGeometry(QRect(190, 90, 51, 22))
        self.AC_KeyboardSeconds.setMaximum(999)
        self.AC_KeyboardMiliseconds = QSpinBox(self.AC_KeyboardTime)
        self.AC_KeyboardMiliseconds.setObjectName(u"AC_KeyboardMiliseconds")
        self.AC_KeyboardMiliseconds.setGeometry(QRect(280, 90, 51, 22))
        self.AC_KeyboardMiliseconds.setMinimum(1)
        self.AC_KeyboardMiliseconds.setMaximum(999)
        self.AC_KeyboardMiliseconds.setValue(100)
        self.label_12 = QLabel(self.AC_KeyboardTime)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 70, 71, 20))
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.AC_KeyboardTime)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(190, 70, 51, 20))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.AC_KeyboardTime)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(110, 70, 51, 20))
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(self.AC_KeyboardTime)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 70, 51, 20))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.AC_KeyboardClickHowManyTimesGroup = QGroupBox(self.AC_Keyboard)
        self.AC_KeyboardClickHowManyTimesGroup.setObjectName(u"AC_KeyboardClickHowManyTimesGroup")
        self.AC_KeyboardClickHowManyTimesGroup.setGeometry(QRect(190, 210, 171, 271))
        self.AC_KeyboardClickNTimes = QRadioButton(self.AC_KeyboardClickHowManyTimesGroup)
        self.AC_KeyboardClickNTimes.setObjectName(u"AC_KeyboardClickNTimes")
        self.AC_KeyboardClickNTimes.setGeometry(QRect(10, 100, 47, 21))
        self.AC_KeyboardClickNTimesN = QSpinBox(self.AC_KeyboardClickHowManyTimesGroup)
        self.AC_KeyboardClickNTimesN.setObjectName(u"AC_KeyboardClickNTimesN")
        self.AC_KeyboardClickNTimesN.setGeometry(QRect(60, 100, 61, 22))
        self.AC_KeyboardClickNTimesN.setMinimum(1)
        self.AC_KeyboardClickNTimesN.setMaximum(9999999)
        self.AC_KeyboardClickNTimesN.setValue(1)
        self.label_16 = QLabel(self.AC_KeyboardClickHowManyTimesGroup)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(130, 100, 21, 21))
        self.AC_KeyboardClickUntilStopped = QRadioButton(self.AC_KeyboardClickHowManyTimesGroup)
        self.AC_KeyboardClickUntilStopped.setObjectName(u"AC_KeyboardClickUntilStopped")
        self.AC_KeyboardClickUntilStopped.setGeometry(QRect(10, 130, 123, 17))
        self.AC_KeyboardClickUntilStopped.setChecked(True)
        self.AC_KeyboardHold = QRadioButton(self.AC_KeyboardClickHowManyTimesGroup)
        self.AC_KeyboardHold.setObjectName(u"AC_KeyboardHold")
        self.AC_KeyboardHold.setGeometry(QRect(10, 160, 80, 17))
        self.AC_KeyboardOptions = QGroupBox(self.AC_Keyboard)
        self.AC_KeyboardOptions.setObjectName(u"AC_KeyboardOptions")
        self.AC_KeyboardOptions.setGeometry(QRect(10, 210, 161, 271))
        self.verticalLayout_2 = QVBoxLayout(self.AC_KeyboardOptions)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_4)

        self.label_17 = QLabel(self.AC_KeyboardOptions)
        self.label_17.setObjectName(u"label_17")

        self.verticalLayout_2.addWidget(self.label_17)

        self.verticalSpacer_5 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_5)

        self.label_18 = QLabel(self.AC_KeyboardOptions)
        self.label_18.setObjectName(u"label_18")

        self.verticalLayout_2.addWidget(self.label_18)

        self.verticalSpacer_6 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_6)

        self.AC_KeyboardStop = QPushButton(self.AC_Keyboard)
        self.AC_KeyboardStop.setObjectName(u"AC_KeyboardStop")
        self.AC_KeyboardStop.setGeometry(QRect(190, 490, 171, 23))
        self.AC_KeyboardStart = QPushButton(self.AC_Keyboard)
        self.AC_KeyboardStart.setObjectName(u"AC_KeyboardStart")
        self.AC_KeyboardStart.setGeometry(QRect(10, 490, 161, 23))
        self.tabs.addTab(self.autoclickerTab, "")
        self.settingsTab = QWidget()
        self.settingsTab.setObjectName(u"settingsTab")
        self.settingsAutosave = QCheckBox(self.settingsTab)
        self.settingsAutosave.setObjectName(u"settingsAutosave")
        self.settingsAutosave.setGeometry(QRect(10, 30, 157, 17))
        self.settingsAutosave.setChecked(True)
        self.settingsDefault = QPushButton(self.settingsTab)
        self.settingsDefault.setObjectName(u"settingsDefault")
        self.settingsDefault.setGeometry(QRect(10, 480, 171, 41))
        self.forceSave = QPushButton(self.settingsTab)
        self.forceSave.setObjectName(u"forceSave")
        self.forceSave.setGeometry(QRect(10, 440, 81, 23))
        self.forceLoad = QPushButton(self.settingsTab)
        self.forceLoad.setObjectName(u"forceLoad")
        self.forceLoad.setGeometry(QRect(100, 440, 81, 23))
        self.label_11 = QLabel(self.settingsTab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(558, 10, 204, 13))
        self.execution_time = QDoubleSpinBox(self.settingsTab)
        self.execution_time.setObjectName(u"execution_time")
        self.execution_time.setGeometry(QRect(570, 420, 71, 22))
        self.execution_time.setMaximum(100.000000000000000)
        self.execution_time.setSingleStep(0.100000000000000)
        self.label_19 = QLabel(self.settingsTab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(560, 390, 110, 26))
        self.tabs.addTab(self.settingsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 792, 21))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.creatorEditorActions.itemDoubleClicked.connect(self.creatorEditorAddToMacro.click)

        self.tabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Automatyczne robienie rzeczy 0.8", None))
#if QT_CONFIG(tooltip)
        self.macroDelete.setToolTip(QCoreApplication.translate("MainWindow", u"Usuwa zaznaczone makro.", None))
#endif // QT_CONFIG(tooltip)
        self.macroDelete.setText(QCoreApplication.translate("MainWindow", u"Usu\u0144", None))
#if QT_CONFIG(tooltip)
        self.macroEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Kopiuje zawarto\u015b\u0107 makra do kreatora makr.", None))
#endif // QT_CONFIG(tooltip)
        self.macroEdit.setText(QCoreApplication.translate("MainWindow", u"Edytuj", None))
#if QT_CONFIG(tooltip)
        self.macroNew.setToolTip(QCoreApplication.translate("MainWindow", u"Otwiera pusty kreator makr.", None))
#endif // QT_CONFIG(tooltip)
        self.macroNew.setText(QCoreApplication.translate("MainWindow", u"Dodaj nowe makro", None))
        self.tabs.setTabText(self.tabs.indexOf(self.macroTab), QCoreApplication.translate("MainWindow", u"Makra", None))
        self.creatorEditorGroup.setTitle(QCoreApplication.translate("MainWindow", u"Kreator makr", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorDeleteFromMacro.setToolTip(QCoreApplication.translate("MainWindow", u"Wymaga aby jaki\u015b element listy komend by\u0142 zaznaczony.\n"
"Pocz\u0105tek p\u0119tli jest nieusuwalny.", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorDeleteFromMacro.setText(QCoreApplication.translate("MainWindow", u"Usu\u0144 z makro", None))
        ___qtreewidgetitem = self.creatorEditorActions.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"Czynno\u015bci", None));

        __sortingEnabled = self.creatorEditorActions.isSortingEnabled()
        self.creatorEditorActions.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.creatorEditorActions.topLevelItem(0)
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"Akcje myszki", None));
        ___qtreewidgetitem2 = ___qtreewidgetitem1.child(0)
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"Przemie\u015b\u0107 kursor", None));
        ___qtreewidgetitem3 = ___qtreewidgetitem1.child(1)
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("MainWindow", u"Klikni\u0119cie", None));
        ___qtreewidgetitem4 = ___qtreewidgetitem1.child(2)
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("MainWindow", u"Podw\u00f3jne klikni\u0119cie", None));
        ___qtreewidgetitem5 = ___qtreewidgetitem1.child(3)
        ___qtreewidgetitem5.setText(0, QCoreApplication.translate("MainWindow", u"Przytrzymaj przycisk myszy", None));
        ___qtreewidgetitem6 = ___qtreewidgetitem1.child(4)
        ___qtreewidgetitem6.setText(0, QCoreApplication.translate("MainWindow", u"Pu\u015b\u0107 przycisk myszy", None));
        ___qtreewidgetitem7 = ___qtreewidgetitem1.child(5)
        ___qtreewidgetitem7.setText(0, QCoreApplication.translate("MainWindow", u"Ruch k\u00f3\u0142ka myszy", None));
        ___qtreewidgetitem8 = self.creatorEditorActions.topLevelItem(1)
        ___qtreewidgetitem8.setText(0, QCoreApplication.translate("MainWindow", u"Akcje klawiatury", None));
        ___qtreewidgetitem9 = ___qtreewidgetitem8.child(0)
        ___qtreewidgetitem9.setText(0, QCoreApplication.translate("MainWindow", u"Kliknij klawisz", None));
        ___qtreewidgetitem10 = ___qtreewidgetitem8.child(1)
        ___qtreewidgetitem10.setText(0, QCoreApplication.translate("MainWindow", u"Przytrzymaj klawisz", None));
        ___qtreewidgetitem11 = ___qtreewidgetitem8.child(2)
        ___qtreewidgetitem11.setText(0, QCoreApplication.translate("MainWindow", u"Pu\u015b\u0107 klawisz", None));
        ___qtreewidgetitem12 = ___qtreewidgetitem8.child(3)
        ___qtreewidgetitem12.setText(0, QCoreApplication.translate("MainWindow", u"Wypisz tekst", None));
        ___qtreewidgetitem13 = ___qtreewidgetitem8.child(4)
        ___qtreewidgetitem13.setText(0, QCoreApplication.translate("MainWindow", u"Pu\u015b\u0107 wszystkie klawisze", None));
        ___qtreewidgetitem14 = self.creatorEditorActions.topLevelItem(2)
        ___qtreewidgetitem14.setText(0, QCoreApplication.translate("MainWindow", u"Logika", None));
        ___qtreewidgetitem15 = ___qtreewidgetitem14.child(0)
        ___qtreewidgetitem15.setText(0, QCoreApplication.translate("MainWindow", u"Czekaj na akcj\u0119 myszy", None));
        ___qtreewidgetitem16 = ___qtreewidgetitem14.child(1)
        ___qtreewidgetitem16.setText(0, QCoreApplication.translate("MainWindow", u"Czekaj na akcj\u0119 klawiatury", None));
        ___qtreewidgetitem17 = ___qtreewidgetitem14.child(2)
        ___qtreewidgetitem17.setText(0, QCoreApplication.translate("MainWindow", u"Czekaj N sekund", None));
        ___qtreewidgetitem18 = ___qtreewidgetitem14.child(3)
        ___qtreewidgetitem18.setText(0, QCoreApplication.translate("MainWindow", u"Wykonaj N razy", None));
        ___qtreewidgetitem19 = self.creatorEditorActions.topLevelItem(3)
        ___qtreewidgetitem19.setText(0, QCoreApplication.translate("MainWindow", u"Nagrane", None));
        self.creatorEditorActions.setSortingEnabled(__sortingEnabled)

#if QT_CONFIG(tooltip)
        self.creatorEditorAddToMacro.setToolTip(QCoreApplication.translate("MainWindow", u"Dodaje element z listy czynno\u015bci do listy komend.", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorAddToMacro.setText(QCoreApplication.translate("MainWindow", u"Dodaj do makro", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorMoveUp.setToolTip(QCoreApplication.translate("MainWindow", u"Przesuwa zaznaczony element listy komend w g\u00f3r\u0119.", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorMoveUp.setText(QCoreApplication.translate("MainWindow", u"\u25b2", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorMoveDown.setToolTip(QCoreApplication.translate("MainWindow", u"Przesuwa zaznaczony element listy komend w d\u00f3\u0142.", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorMoveDown.setText(QCoreApplication.translate("MainWindow", u"\u25bc", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorSave.setToolTip(QCoreApplication.translate("MainWindow", u"Wymaga aby lista komend i nazwa makra nie by\u0142y puste.", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorSave.setText(QCoreApplication.translate("MainWindow", u"Zapisz makro", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorName.setToolTip(QCoreApplication.translate("MainWindow", u"Nazwa nie mo\u017ce zawiera\u0107 znak\u00f3w: /?%*:|\"<>.", None))
#endif // QT_CONFIG(tooltip)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Nazwa makra", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorClear.setToolTip(QCoreApplication.translate("MainWindow", u"Usuwa wszystkie elementy z listy komend.", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorClear.setText(QCoreApplication.translate("MainWindow", u"Wyczy\u015b\u0107 edytor", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorDeleteFromActions.setToolTip(QCoreApplication.translate("MainWindow", u"Wymaga aby jakie\u015b nagranie w li\u015bcie czynno\u015bci by\u0142o zaznaczone", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorDeleteFromActions.setText(QCoreApplication.translate("MainWindow", u"Usu\u0144 nagranie", None))
#if QT_CONFIG(tooltip)
        self.creatorEditorNewRecording.setToolTip(QCoreApplication.translate("MainWindow", u"Otwiera pusty edytor nagra\u0144.", None))
#endif // QT_CONFIG(tooltip)
        self.creatorEditorNewRecording.setText(QCoreApplication.translate("MainWindow", u"Nowe nagranie", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Lista komend tworz\u0105cych makro", None))
#if QT_CONFIG(tooltip)
        self.previewButton.setToolTip(QCoreApplication.translate("MainWindow", u"Odtwarza list\u0119 komend.", None))
#endif // QT_CONFIG(tooltip)
        self.previewButton.setText(QCoreApplication.translate("MainWindow", u"Odtw\u00f3rz", None))
        self.tabs.setTabText(self.tabs.indexOf(self.creatorTab), QCoreApplication.translate("MainWindow", u"Kreator", None))
        self.AC_Mouse.setTitle(QCoreApplication.translate("MainWindow", u"Autoclicker myszy", None))
        self.AC_Time.setTitle(QCoreApplication.translate("MainWindow", u"Odst\u0119p czasowy mi\u0119dzy klikni\u0119ciami", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Milisekundy", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Sekundy", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Minuty", None))
#if QT_CONFIG(accessibility)
        self.label_4.setAccessibleName(QCoreApplication.translate("MainWindow", u"0", None))
#endif // QT_CONFIG(accessibility)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Godziny", None))
        self.AC_ClickHowManyTimesGroup.setTitle(QCoreApplication.translate("MainWindow", u"Ile razy ma klika\u0107", None))
        self.AC_ClickNTimes.setText(QCoreApplication.translate("MainWindow", u"Klikaj", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"razy", None))
        self.AC_ClickUntilStopped.setText(QCoreApplication.translate("MainWindow", u"Klikaj do zatrzymania", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Opcje", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Wybierz przycisk myszy", None))
        self.AC_WhichButton.setItemText(0, QCoreApplication.translate("MainWindow", u"Lewy", None))
        self.AC_WhichButton.setItemText(1, QCoreApplication.translate("MainWindow", u"\u015arodkowy", None))
        self.AC_WhichButton.setItemText(2, QCoreApplication.translate("MainWindow", u"Prawy", None))

        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Skr\u00f3t klawiszowy", None))
        self.AC_Stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.AC_Start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.AC_Keyboard.setTitle(QCoreApplication.translate("MainWindow", u"Autoclicker klawiatury", None))
        self.AC_KeyboardTime.setTitle(QCoreApplication.translate("MainWindow", u"Odst\u0119p czasowy mi\u0119dzy klikni\u0119ciami", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Milisekundy", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Sekundy", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Minuty", None))
#if QT_CONFIG(accessibility)
        self.label_15.setAccessibleName(QCoreApplication.translate("MainWindow", u"0", None))
#endif // QT_CONFIG(accessibility)
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Godziny", None))
        self.AC_KeyboardClickHowManyTimesGroup.setTitle(QCoreApplication.translate("MainWindow", u"Ile razy ma klika\u0107", None))
        self.AC_KeyboardClickNTimes.setText(QCoreApplication.translate("MainWindow", u"Klikaj", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"razy", None))
        self.AC_KeyboardClickUntilStopped.setText(QCoreApplication.translate("MainWindow", u"Klikaj do zatrzymania", None))
        self.AC_KeyboardHold.setText(QCoreApplication.translate("MainWindow", u"Przytrzymaj", None))
        self.AC_KeyboardOptions.setTitle(QCoreApplication.translate("MainWindow", u"Opcje", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Wybierz klawisz/klawisze", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Skr\u00f3t klawiszowy", None))
        self.AC_KeyboardStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.AC_KeyboardStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.tabs.setTabText(self.tabs.indexOf(self.autoclickerTab), QCoreApplication.translate("MainWindow", u"Autoclicker", None))
        self.settingsAutosave.setText(QCoreApplication.translate("MainWindow", u"Autozapis po ka\u017cdej zmianie", None))
        self.settingsDefault.setText(QCoreApplication.translate("MainWindow", u"Przywr\u00f3\u0107 domy\u015blne ustawienia", None))
#if QT_CONFIG(tooltip)
        self.forceSave.setToolTip(QCoreApplication.translate("MainWindow", u"Zapisz obecne ustawienia.", None))
#endif // QT_CONFIG(tooltip)
        self.forceSave.setText(QCoreApplication.translate("MainWindow", u"Zapisz", None))
#if QT_CONFIG(tooltip)
        self.forceLoad.setToolTip(QCoreApplication.translate("MainWindow", u"Wczytaj zapisane ustawienia.", None))
#endif // QT_CONFIG(tooltip)
        self.forceLoad.setText(QCoreApplication.translate("MainWindow", u"Wczytaj", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Skr\u00f3t przerywaj\u0105cy wszystkie odtwarzania", None))
#if QT_CONFIG(tooltip)
        self.execution_time.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.execution_time.setSuffix(QCoreApplication.translate("MainWindow", u"ms", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Bazowy odst\u0119p mi\u0119dzy\n"
"czynno\u015bciami w makrze", None))
        self.tabs.setTabText(self.tabs.indexOf(self.settingsTab), QCoreApplication.translate("MainWindow", u"Ustawienia", None))
    # retranslateUi

